# Generated by Django 2.0.4 on 2019-10-16 07:05

from django.db import migrations, models
import django.db.models.deletion
import websearch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cjdj_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dizhi', models.TextField(max_length=500)),
                ('lx', models.TextField(max_length=500)),
                ('mianji', models.FloatField()),
                ('zongjia', models.FloatField()),
                ('dj', models.FloatField()),
                ('cjdate', models.DateField()),
                ('down', models.FileField(upload_to=websearch.models.upload_to)),
                ('area', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loginname', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('tel', models.IntegerField(null=True)),
                ('cer', models.IntegerField(null=True)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websearch.user')),
            ],
        ),
    ]
