# Generated by Django 2.0.4 on 2019-12-17 07:38

from django.db import migrations, models
import django.db.models.deletion
import websearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('websearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='名称')),
                ('about', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='First_classInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='名称')),
                ('context', models.TextField(max_length=1000, verbose_name='内容')),
                ('fj1', models.FileField(upload_to=websearch.models.upload_to, verbose_name='附件1')),
                ('fj1n', models.TextField(max_length=100, verbose_name='附件1名称')),
                ('fj2n', models.TextField(max_length=100, verbose_name='附件2名称')),
                ('fj3n', models.TextField(max_length=100, verbose_name='附件3名称')),
                ('fj4n', models.TextField(max_length=100, verbose_name='附件4名称')),
                ('fj2', models.FileField(upload_to=websearch.models.upload_to, verbose_name='附件2')),
                ('fj3', models.FileField(upload_to=websearch.models.upload_to, verbose_name='附件3')),
                ('fj4', models.FileField(upload_to=websearch.models.upload_to, verbose_name='附件4')),
            ],
        ),
        migrations.CreateModel(
            name='Second_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='名称')),
                ('about', models.TextField(max_length=500)),
                ('fid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websearch.First_class')),
            ],
        ),
        migrations.CreateModel(
            name='Second_classInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='名称')),
                ('context', models.TextField(max_length=1000, verbose_name='内容')),
                ('fj1', models.FileField(upload_to=websearch.models.upload_to, verbose_name='附件1')),
                ('fj1n', models.TextField(max_length=100, verbose_name='附件1名称')),
                ('fj2n', models.TextField(max_length=100, verbose_name='附件2名称')),
                ('fj3n', models.TextField(max_length=100, verbose_name='附件3名称')),
                ('fj4n', models.TextField(max_length=100, verbose_name='附件4名称')),
                ('fj2', models.FileField(upload_to=websearch.models.upload_to, verbose_name='附件2')),
                ('fj3', models.FileField(upload_to=websearch.models.upload_to, verbose_name='附件3')),
                ('fj4', models.FileField(upload_to=websearch.models.upload_to, verbose_name='附件4')),
                ('fid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websearch.Second_class')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cjdj_info',
            options={'verbose_name_plural': '成交单价'},
        ),
        migrations.AlterField(
            model_name='cjdj_info',
            name='area',
            field=models.TextField(max_length=500, null=True, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='cjdj_info',
            name='cjdate',
            field=models.DateField(verbose_name='成交日期'),
        ),
        migrations.AlterField(
            model_name='cjdj_info',
            name='dizhi',
            field=models.TextField(max_length=500, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='cjdj_info',
            name='dj',
            field=models.FloatField(verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='cjdj_info',
            name='down',
            field=models.FileField(upload_to=websearch.models.upload_to, verbose_name='下载地址'),
        ),
        migrations.AlterField(
            model_name='cjdj_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cjdj_info',
            name='lx',
            field=models.TextField(max_length=500, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='cjdj_info',
            name='mianji',
            field=models.FloatField(verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='cjdj_info',
            name='zongjia',
            field=models.FloatField(verbose_name='总价'),
        ),
        migrations.AddField(
            model_name='first_classinfo',
            name='fid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websearch.Second_class'),
        ),
    ]
