# Generated by Django 2.0.4 on 2019-12-17 08:33

from django.db import migrations, models
import websearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('websearch', '0003_auto_20191217_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_class',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj1',
            field=models.FileField(null=True, upload_to=websearch.models.upload_to, verbose_name='附件1'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj1n',
            field=models.TextField(max_length=100, null=True, verbose_name='附件1名称'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj2',
            field=models.FileField(null=True, upload_to=websearch.models.upload_to, verbose_name='附件2'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj2n',
            field=models.TextField(max_length=100, null=True, verbose_name='附件2名称'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj3',
            field=models.FileField(null=True, upload_to=websearch.models.upload_to, verbose_name='附件3'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj3n',
            field=models.TextField(max_length=100, null=True, verbose_name='附件3名称'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj4',
            field=models.FileField(null=True, upload_to=websearch.models.upload_to, verbose_name='附件4'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj4n',
            field=models.TextField(max_length=100, null=True, verbose_name='附件4名称'),
        ),
        migrations.AlterField(
            model_name='second_class',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='context',
            field=models.TextField(max_length=1000, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj1n',
            field=models.TextField(max_length=100, null=True, verbose_name='附件1名称'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj2',
            field=models.FileField(null=True, upload_to=websearch.models.upload_to, verbose_name='附件2'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj2n',
            field=models.TextField(max_length=100, null=True, verbose_name='附件2名称'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj3',
            field=models.FileField(null=True, upload_to=websearch.models.upload_to, verbose_name='附件3'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj3n',
            field=models.TextField(max_length=100, null=True, verbose_name='附件3名称'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj4',
            field=models.FileField(null=True, upload_to=websearch.models.upload_to, verbose_name='附件4'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj4n',
            field=models.TextField(max_length=100, null=True, verbose_name='附件4名称'),
        ),
    ]
