# Generated by Django 2.0.4 on 2019-12-18 03:04

from django.db import migrations, models
import django.db.models.deletion
import websearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('websearch', '0004_auto_20191217_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cjdj_info',
            name='area',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='first_class',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj1',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件1'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj1n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件1名称'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj2',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件2'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj2n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件2名称'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj3',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件3'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj3n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件3名称'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj4',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件4'),
        ),
        migrations.AlterField(
            model_name='first_classinfo',
            name='fj4n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件4名称'),
        ),
        migrations.AlterField(
            model_name='second_class',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='second_class',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websearch.First_class'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='context',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj1n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件1名称'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj2',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件2'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj2n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件2名称'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj3',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件3'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj3n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件3名称'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj4',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件4'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fj4n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件4名称'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='cer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
