# Generated by Django 2.0.4 on 2019-12-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websearch', '0005_auto_20191218_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='first_class',
            options={'verbose_name_plural': '一级目录'},
        ),
        migrations.AlterModelOptions(
            name='second_class',
            options={'verbose_name_plural': '二级目录'},
        ),
    ]
