# Generated by Django 2.0.4 on 2019-12-19 03:40

from django.db import migrations, models
import django.db.models.deletion
import websearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('websearch', '0006_auto_20191219_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='second_classinfo',
            name='fj5',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件5'),
        ),
        migrations.AddField(
            model_name='second_classinfo',
            name='fj5n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件5名称'),
        ),
        migrations.AddField(
            model_name='second_classinfo',
            name='fj6',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件6'),
        ),
        migrations.AddField(
            model_name='second_classinfo',
            name='fj6n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件6名称'),
        ),
        migrations.AddField(
            model_name='second_classinfo',
            name='fj7',
            field=models.FileField(blank=True, null=True, upload_to=websearch.models.upload_to, verbose_name='附件7'),
        ),
        migrations.AddField(
            model_name='second_classinfo',
            name='fj7n',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='附件7名称'),
        ),
        migrations.AlterField(
            model_name='second_class',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='websearch.First_class'),
        ),
        migrations.AlterField(
            model_name='second_classinfo',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondinfo', to='websearch.Second_class'),
        ),
    ]
